// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $bsky from "./routes/bsky.ts";
import * as $cv from "./routes/cv.tsx";
import * as $index from "./routes/index.tsx";
import * as $mastodon from "./routes/mastodon.ts";
import * as $mfl2022benches from "./routes/mfl2022benches.ts";
import * as $test from "./routes/test.ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/bsky.ts": $bsky,
    "./routes/cv.tsx": $cv,
    "./routes/index.tsx": $index,
    "./routes/mastodon.ts": $mastodon,
    "./routes/mfl2022benches.ts": $mfl2022benches,
    "./routes/test.ts": $test,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
