// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/cv.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/mastodon.ts";
import * as $4 from "./routes/mfl2022benches.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/cv.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/mastodon.ts": $3,
    "./routes/mfl2022benches.ts": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
